repos:
  - repo: local
    hooks:
      - id: fmt
        name: cargo fmt
        entry: cargo fmt --
        language: system
        files: \.rs$
        pass_filenames: false
        stages: [pre-commit]

      - id: cargo-check
        name: cargo check
        entry: cargo check
        language: system
        files: \.rs$
        pass_filenames: false
        stages: [pre-commit]

      - id: cargo-clippy
        name: cargo clippy
        entry: cargo clippy -- -D warnings
        language: system
        files: \.rs$
        pass_filenames: false
        stages: [pre-commit]

      - id: aarch64-build
        name: aarch64-build
        entry: ./scripts/aarch64-build.sh
        language: system
        files: \.rs$
        pass_filenames: false
        stages: [pre-push]