[package]
name = "clonebox"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
description = "Clonebox implements a Linux subset of the OCI runtime specification, the same scope as runc"
authors = ["pan-ic <dev@pan.fr>"]

[dependencies]
anyhow = "1.0.103"
clap = { version = "4.6.1", features = ["derive"] }
libc = "0.2.186"
nix = { version = "0.31.3", features = ["fs", "hostname", "mount", "process", "sched", "signal"] }
thiserror = "2.0.18"
