[package]
name = "cloneboxd"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.103"
nix = { version = "0.31.3", features = ["process"]}
tonic = "*"
prost = "0.14"
tonic-prost = "*"
tokio = { version = "1.0", features = ["macros", "net", "process", "rt-multi-thread"] }
tokio-stream = "0.1.19"
serde_json = "1"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter", "std"] }
clonebox-core = { path = "../clonebox-core" }

[build-dependencies]
tonic-prost-build = "*"
