syntax = "proto3";
package clonebox_tasks;

service CloneboxTasks {
  rpc Create(CreateRequest) returns (CreateResponse);
  rpc Start(StartRequest) returns (StartResponse);
  rpc State(StateRequest) returns (StateResponse);
  rpc Kill(KillRequest) returns (KillResponse);
  rpc Delete(DeleteRequest) returns (DeleteResponse);
  rpc Pause(PauseRequest) returns (PauseResponse);
  rpc Resume(ResumeRequest) returns (ResumeResponse);
  rpc Exec(ExecRequest) returns (ExecResponse);
  rpc Wait(WaitRequest) returns (WaitResponse);
  rpc List(ListRequest) returns (ListResponse);
}

enum ContainerState {
  CONTAINER_STATE_UNKNOWN = 0;
  CREATING = 1;
  CREATED = 2;
  RUNNING = 3;
  STOPPED = 4;
  PAUSED = 5;
}

message State {
    string oci_version = 1;
    string id = 2;
    ContainerState status = 3;
    optional int32 pid = 4;
    string bundle = 5;
    map<string, string> annotations = 6;
}

message CreateRequest {
  string container_id = 1;
  string config_path = 2;
}
message CreateResponse {}

message StartRequest {
  string container_id = 1;
}
message StartResponse {}

message StateRequest {
  string container_id = 1;
}
message StateResponse {
  State state = 1;
}

message KillRequest {
  string container_id = 1;
}
message KillResponse {}

message DeleteRequest {
  string container_id = 1;
  bool force = 2;
}
message DeleteResponse {}

message PauseRequest {
 string container_id = 1; 
}
message PauseResponse {}

message ResumeRequest {
  string container_id = 1;
}
message ResumeResponse {}

message ExecRequest {
  string container_id = 1;
  repeated string commands = 2;
}
message ExecResponse {}

message WaitRequest {
  string id = 1;
}
message WaitResponse {
  int32 exit = 1;
}

message ListRequest {}
message ListResponse {
  repeated State states = 1;
}

/*
message ListRequest {}
message ListResponse {
  map <string, State> containers = 1;
}
*/
