#!/bin/sh
set -e
VERSION=3.20.0
URL="https://dl-cdn.alpinelinux.org/alpine/v3.20/releases/x86_64/alpine-minirootfs-${VERSION}-x86_64.tar.gz"
mkdir -p rootfs
curl -sL "$URL" | tar -xz -C rootfs
echo "rootfs ready at ./rootfs"
