name: deny.yml
run-name: deny
on: [push]
jobs:
  deny:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo install cargo-deny --locked
      - run: cargo deny check